CREATE TYPE "Role" AS ENUM ('CUSTOMER', 'RETAILER', 'ADMIN');
CREATE TYPE "RetailerStatus" AS ENUM ('PENDING', 'APPROVED', 'SUSPENDED', 'REJECTED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'CONFIRMED', 'PACKING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'REFUNDED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED');
CREATE TYPE "PaymentMethod" AS ENUM ('UPI', 'CARD', 'COD', 'WALLET');
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED');
CREATE TYPE "NotificationType" AS ENUM ('ORDER', 'INVENTORY', 'PROMOTION', 'SYSTEM');
CREATE TYPE "AddressType" AS ENUM ('HOME', 'WORK', 'OTHER');

CREATE TABLE "users" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"phone" TEXT,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'CUSTOMER',"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "retailers" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"businessName" TEXT NOT NULL,"legalName" TEXT,"gstin" TEXT,"status" "RetailerStatus" NOT NULL DEFAULT 'PENDING',"commissionBps" INTEGER NOT NULL DEFAULT 750,"approvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "retailers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "stores" ("id" TEXT NOT NULL,"retailerId" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"description" TEXT,"phone" TEXT,"email" TEXT,"addressLine1" TEXT NOT NULL,"addressLine2" TEXT,"city" TEXT NOT NULL,"state" TEXT NOT NULL,"postalCode" TEXT NOT NULL,"latitude" DECIMAL(9,6) NOT NULL,"longitude" DECIMAL(9,6) NOT NULL,"serviceRadiusKm" DECIMAL(5,2) NOT NULL DEFAULT 5,"minimumOrderPaise" INTEGER NOT NULL DEFAULT 0,"deliveryFeePaise" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"opensAt" TEXT,"closesAt" TEXT,"rating" DECIMAL(3,2) NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "stores_pkey" PRIMARY KEY ("id"));
CREATE TABLE "categories" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"imageUrl" TEXT,"parentId" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"sortOrder" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "categories_pkey" PRIMARY KEY ("id"));
CREATE TABLE "products" ("id" TEXT NOT NULL,"categoryId" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"brand" TEXT,"description" TEXT,"unitLabel" TEXT,"barcode" TEXT,"imageUrls" TEXT[],"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "products_pkey" PRIMARY KEY ("id"));
CREATE TABLE "inventory" ("id" TEXT NOT NULL,"storeId" TEXT NOT NULL,"productId" TEXT NOT NULL,"sku" TEXT NOT NULL,"pricePaise" INTEGER NOT NULL,"mrpPaise" INTEGER NOT NULL,"costPaise" INTEGER,"stock" INTEGER NOT NULL DEFAULT 0,"reservedStock" INTEGER NOT NULL DEFAULT 0,"lowStockAt" INTEGER NOT NULL DEFAULT 10,"isAvailable" BOOLEAN NOT NULL DEFAULT true,"version" INTEGER NOT NULL DEFAULT 1,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "inventory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "addresses" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" "AddressType" NOT NULL DEFAULT 'HOME',"label" TEXT,"recipientName" TEXT NOT NULL,"phone" TEXT NOT NULL,"line1" TEXT NOT NULL,"line2" TEXT,"landmark" TEXT,"city" TEXT NOT NULL,"state" TEXT NOT NULL,"postalCode" TEXT NOT NULL,"latitude" DECIMAL(9,6),"longitude" DECIMAL(9,6),"isDefault" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "addresses_pkey" PRIMARY KEY ("id"));
CREATE TABLE "orders" ("id" TEXT NOT NULL,"orderNumber" TEXT NOT NULL,"userId" TEXT NOT NULL,"addressId" TEXT NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'PENDING',"subtotalPaise" INTEGER NOT NULL,"deliveryPaise" INTEGER NOT NULL DEFAULT 0,"discountPaise" INTEGER NOT NULL DEFAULT 0,"platformFeePaise" INTEGER NOT NULL DEFAULT 0,"totalPaise" INTEGER NOT NULL,"savingsPaise" INTEGER NOT NULL DEFAULT 0,"idempotencyKey" TEXT,"notes" TEXT,"placedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "orders_pkey" PRIMARY KEY ("id"));
CREATE TABLE "store_orders" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"storeId" TEXT NOT NULL,"status" "OrderStatus" NOT NULL DEFAULT 'PENDING',"subtotalPaise" INTEGER NOT NULL,"deliveryPaise" INTEGER NOT NULL DEFAULT 0,"totalPaise" INTEGER NOT NULL,"acceptedAt" TIMESTAMP(3),"readyAt" TIMESTAMP(3),"deliveredAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "store_orders_pkey" PRIMARY KEY ("id"));
CREATE TABLE "order_items" ("id" TEXT NOT NULL,"storeOrderId" TEXT NOT NULL,"productId" TEXT NOT NULL,"inventoryId" TEXT NOT NULL,"productName" TEXT NOT NULL,"sku" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"unitPricePaise" INTEGER NOT NULL,"mrpPaise" INTEGER NOT NULL,"totalPaise" INTEGER NOT NULL,CONSTRAINT "order_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"provider" TEXT NOT NULL,"providerRef" TEXT,"method" "PaymentMethod" NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"amountPaise" INTEGER NOT NULL,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "payments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "subscriptions" ("id" TEXT NOT NULL,"retailerId" TEXT NOT NULL,"plan" TEXT NOT NULL,"status" "SubscriptionStatus" NOT NULL DEFAULT 'TRIALING',"amountPaise" INTEGER NOT NULL,"interval" TEXT NOT NULL DEFAULT 'month',"providerRef" TEXT,"currentStart" TIMESTAMP(3) NOT NULL,"currentEnd" TIMESTAMP(3) NOT NULL,"cancelledAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "wishlist" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"productId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "wishlist_pkey" PRIMARY KEY ("id"));
CREATE TABLE "reviews" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"storeId" TEXT,"productId" TEXT,"rating" INTEGER NOT NULL,"title" TEXT,"body" TEXT,"isVerified" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "reviews_pkey" PRIMARY KEY ("id"));
CREATE TABLE "notifications" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" "NotificationType" NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"data" JSONB,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"));
CREATE TABLE "analytics" ("id" TEXT NOT NULL,"userId" TEXT,"name" TEXT NOT NULL,"entityType" TEXT,"entityId" TEXT,"properties" JSONB,"sessionId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "analytics_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_phone_key" ON "users"("phone");
CREATE INDEX "users_role_isActive_idx" ON "users"("role", "isActive");
CREATE UNIQUE INDEX "retailers_userId_key" ON "retailers"("userId");
CREATE UNIQUE INDEX "retailers_gstin_key" ON "retailers"("gstin");
CREATE INDEX "retailers_status_createdAt_idx" ON "retailers"("status", "createdAt");
CREATE UNIQUE INDEX "stores_slug_key" ON "stores"("slug");
CREATE INDEX "stores_retailerId_isActive_idx" ON "stores"("retailerId", "isActive");
CREATE INDEX "stores_city_isActive_idx" ON "stores"("city", "isActive");
CREATE INDEX "stores_latitude_longitude_idx" ON "stores"("latitude", "longitude");
CREATE UNIQUE INDEX "categories_slug_key" ON "categories"("slug");
CREATE INDEX "categories_parentId_sortOrder_idx" ON "categories"("parentId", "sortOrder");
CREATE UNIQUE INDEX "products_slug_key" ON "products"("slug");
CREATE UNIQUE INDEX "products_barcode_key" ON "products"("barcode");
CREATE INDEX "products_categoryId_isActive_idx" ON "products"("categoryId", "isActive");
CREATE INDEX "products_name_idx" ON "products"("name");
CREATE INDEX "inventory_productId_isAvailable_pricePaise_idx" ON "inventory"("productId", "isAvailable", "pricePaise");
CREATE INDEX "inventory_storeId_stock_idx" ON "inventory"("storeId", "stock");
CREATE UNIQUE INDEX "inventory_storeId_sku_key" ON "inventory"("storeId", "sku");
CREATE UNIQUE INDEX "inventory_storeId_productId_key" ON "inventory"("storeId", "productId");
CREATE INDEX "addresses_userId_isDefault_idx" ON "addresses"("userId", "isDefault");
CREATE UNIQUE INDEX "orders_orderNumber_key" ON "orders"("orderNumber");
CREATE UNIQUE INDEX "orders_idempotencyKey_key" ON "orders"("idempotencyKey");
CREATE INDEX "orders_userId_placedAt_idx" ON "orders"("userId", "placedAt");
CREATE INDEX "orders_status_placedAt_idx" ON "orders"("status", "placedAt");
CREATE INDEX "store_orders_storeId_status_createdAt_idx" ON "store_orders"("storeId", "status", "createdAt");
CREATE UNIQUE INDEX "store_orders_orderId_storeId_key" ON "store_orders"("orderId", "storeId");
CREATE INDEX "order_items_productId_idx" ON "order_items"("productId");
CREATE UNIQUE INDEX "payments_providerRef_key" ON "payments"("providerRef");
CREATE INDEX "payments_orderId_status_idx" ON "payments"("orderId", "status");
CREATE UNIQUE INDEX "subscriptions_providerRef_key" ON "subscriptions"("providerRef");
CREATE INDEX "subscriptions_status_currentEnd_idx" ON "subscriptions"("status", "currentEnd");
CREATE UNIQUE INDEX "wishlist_userId_productId_key" ON "wishlist"("userId", "productId");
CREATE INDEX "reviews_storeId_createdAt_idx" ON "reviews"("storeId", "createdAt");
CREATE INDEX "reviews_productId_createdAt_idx" ON "reviews"("productId", "createdAt");
CREATE INDEX "notifications_userId_readAt_createdAt_idx" ON "notifications"("userId", "readAt", "createdAt");
CREATE INDEX "analytics_name_createdAt_idx" ON "analytics"("name", "createdAt");
CREATE INDEX "analytics_entityType_entityId_createdAt_idx" ON "analytics"("entityType", "entityId", "createdAt");

ALTER TABLE "retailers" ADD CONSTRAINT "retailers_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "stores" ADD CONSTRAINT "stores_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "retailers"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "categories" ADD CONSTRAINT "categories_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "products" ADD CONSTRAINT "products_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "addresses" ADD CONSTRAINT "addresses_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "orders" ADD CONSTRAINT "orders_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "addresses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "store_orders" ADD CONSTRAINT "store_orders_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "store_orders" ADD CONSTRAINT "store_orders_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_storeOrderId_fkey" FOREIGN KEY ("storeOrderId") REFERENCES "store_orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_inventoryId_fkey" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "retailers"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "wishlist" ADD CONSTRAINT "wishlist_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "wishlist" ADD CONSTRAINT "wishlist_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "analytics" ADD CONSTRAINT "analytics_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
