"use client";
import { useState } from "react";
import { Download, Plus, Search, Upload } from "lucide-react";
import { products } from "@/lib/data";
import { Button, Pill } from "@/components/ui";

export default function InventoryPage() {
 const [stocks,setStocks]=useState(Object.fromEntries(products.map(p=>[p.id,p.stock])));
 return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="font-display text-3xl font-extrabold">Inventory</h1><p className="mt-1 text-sm text-slate-500">Live catalog for Gupta General Store</p></div><div className="flex gap-2"><Button variant="secondary"><Upload size={16}/>Import CSV</Button><Button><Plus size={16}/>Add product</Button></div></div><div className="mt-7 flex gap-3"><label className="flex h-11 flex-1 items-center gap-3 rounded-xl border bg-white px-4 dark:border-slate-700 dark:bg-slate-900"><Search size={16} className="text-slate-400"/><input className="w-full bg-transparent text-sm outline-none" placeholder="Search inventory or SKU"/></label><Button variant="secondary"><Download size={16}/><span className="hidden sm:inline">Export</span></Button></div>
 <div className="mt-5 overflow-hidden rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400 dark:bg-slate-800"><tr>{["Product","SKU","Price","Stock","Status","Updated"].map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t dark:border-slate-800"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-slate-100 text-xl dark:bg-slate-800">{p.emoji}</span><div><b className="block text-xs">{p.name}</b><span className="text-[10px] text-slate-400">{p.unit}</span></div></div></td><td className="px-5 text-xs text-slate-500">BS-{p.id.toUpperCase()}-01</td><td className="px-5 font-semibold">₹{p.price}</td><td className="px-5"><input type="number" value={stocks[p.id]} onChange={e=>setStocks({...stocks,[p.id]:Number(e.target.value)})} className="w-16 rounded-lg border bg-transparent px-2 py-1.5 text-xs outline-brand-500 dark:border-slate-700"/></td><td className="px-5"><Pill className={stocks[p.id]===0?"border-rose-200 bg-rose-50 text-rose-700":stocks[p.id]<15?"border-amber-200 bg-amber-50 text-amber-700":""}>{stocks[p.id]===0?"Out of stock":stocks[p.id]<15?"Low stock":"In stock"}</Pill></td><td className="px-5 text-xs text-slate-400">Just now</td></tr>)}</tbody></table></div></div></>;
}
