import { Check, Home, MapPin, PackageCheck, Phone, Store, Truck } from "lucide-react";
import { Button, Pill } from "@/components/ui";
import { createElement } from "react";

export default function OrderTrackingPage() {
  const steps = [[PackageCheck,"Order confirmed","6:02 PM",true],[Store,"Stores are packing","6:08 PM",true],[Truck,"Out for delivery","Expected 6:25 PM",false],[Home,"Delivered","By 6:30 PM",false]];
  return <div className="min-h-screen bg-slate-50 py-10 dark:bg-slate-950"><div className="mx-auto max-w-4xl px-4 sm:px-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Pill>Order #BS240618</Pill><h1 className="mt-4 font-display text-4xl font-extrabold">Your order is being packed.</h1><p className="mt-2 text-slate-500">Two local stores are preparing your Smart Basket.</p></div><Button variant="secondary"><Phone size={16}/>Get help</Button></div>
	    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_300px]"><div className="rounded-3xl border bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="relative space-y-0">{steps.map(([Icon,title,time,done],i)=><div key={title as string} className="relative flex gap-4 pb-9 last:pb-0">{i<steps.length-1&&<span className={`absolute left-[19px] top-10 h-full w-0.5 ${done?"bg-brand-500":"bg-slate-200 dark:bg-slate-700"}`}/>}<span className={`relative z-10 grid size-10 shrink-0 place-items-center rounded-full ${done?"bg-brand-500 text-white":"border-2 bg-white text-slate-300 dark:bg-slate-900"}`}>{done?<Check size={17}/>:createElement(Icon as typeof Store,{size:17})}</span><div><h3 className={`font-semibold ${!done&&i>2?"text-slate-400":""}`}>{title as string}</h3><p className="mt-1 text-xs text-slate-500">{time as string}</p>{i===1&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-800">Gupta General and Fresh Basket are packing 3 items.</div>}</div></div>)}</div></div>
      <aside className="space-y-4"><div className="rounded-2xl bg-ink p-5 text-white"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-brand-500"><Truck size={18}/></span><div><p className="text-xs text-slate-400">Estimated arrival</p><p className="font-display text-xl font-bold">6:25 – 6:30 PM</p></div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/2 rounded-full bg-brand-400"/></div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex gap-3"><MapPin size={18} className="text-brand-500"/><div><p className="text-sm font-semibold">Delivering to Home</p><p className="mt-1 text-xs leading-5 text-slate-500">24, 12th Main, Indiranagar<br/>Bengaluru 560038</p></div></div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><p className="text-sm font-semibold">Payment summary</p><div className="mt-3 flex justify-between text-sm text-slate-500"><span>Paid via UPI</span><b className="text-ink dark:text-white">₹355</b></div></div></aside></div>
  </div></div>;
}
