"use client";

import { useState } from "react";
import { ArrowRight, Check, ChevronRight, Info, MapPin, Minus, Plus, Sparkles, Store, Truck } from "lucide-react";
import { basketItems } from "@/lib/data";
import { money } from "@/lib/utils";
import { Button, Pill } from "@/components/ui";

export default function SmartBasketPage() {
  const [mode, setMode] = useState<"mixed" | "single">("mixed");
  const total = mode === "mixed" ? 350 : 385;
  return <div className="min-h-screen bg-slate-50 py-10 dark:bg-slate-950"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Pill><Sparkles size={12} /> Smart Basket Engine™</Pill><h1 className="mt-4 font-display text-4xl font-extrabold tracking-tight sm:text-5xl">Your basket, optimized.</h1><p className="mt-3 max-w-xl text-slate-500">We checked 27 combinations across 3 nearby stores in 0.4 seconds.</p></div><div className="rounded-xl border bg-white p-1 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900"><button onClick={() => setMode("mixed")} className={`rounded-lg px-4 py-2 ${mode === "mixed" ? "bg-ink text-white dark:bg-white dark:text-ink" : "text-slate-500"}`}>Best combination</button><button onClick={() => setMode("single")} className={`rounded-lg px-4 py-2 ${mode === "single" ? "bg-ink text-white dark:bg-white dark:text-ink" : "text-slate-500"}`}>One store</button></div></div>
    <div className="mt-9 grid gap-6 lg:grid-cols-[1fr_390px]">
      <div className="space-y-5">
        <div className="overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b p-5 dark:border-slate-800"><div><h2 className="font-bold">3 items in your basket</h2><p className="text-xs text-slate-500">Prices updated just now</p></div><button className="text-sm font-semibold text-brand-600">Add items</button></div>
          {basketItems.map((item, i) => <div key={item.name} className="grid grid-cols-[48px_1fr_auto] items-center gap-4 border-b p-5 last:border-0 dark:border-slate-800"><div className="grid size-12 place-items-center rounded-xl bg-slate-100 text-2xl dark:bg-slate-800">{["🍚","🌻","🫘"][i]}</div><div><h3 className="font-semibold">{item.name}</h3><p className="mt-1 text-xs text-slate-500">1 kg · Best at {item.best}</p><div className="mt-2 flex items-center gap-1 text-xs font-semibold text-brand-600"><Check size={13} /> Lowest nearby price</div></div><div className="text-right"><p className="font-bold">{money(Math.min(item.a,item.b,item.c))}</p><div className="mt-2 flex items-center rounded-lg border dark:border-slate-700"><button className="p-1.5"><Minus size={12}/></button><span className="px-2 text-xs">1</span><button className="p-1.5"><Plus size={12}/></button></div></div></div>)}
        </div>
        <div className="rounded-3xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Store comparison</h2><div className="mt-4 space-y-3">{[["Gupta General Store",390,18],["Fresh Basket",390,22],["Apna Bazaar",385,28]].map(([name,price,eta], i) => <div key={name} className="flex items-center gap-4 rounded-2xl border p-4 dark:border-slate-700"><span className={`grid size-10 place-items-center rounded-xl ${i===2?"bg-brand-500 text-white":"bg-slate-100 dark:bg-slate-800"}`}><Store size={18}/></span><div className="flex-1"><p className="text-sm font-semibold">{name}</p><p className="text-xs text-slate-500">{eta} min · All items available</p></div><div className="text-right"><p className="font-bold">{money(price as number)}</p>{i===2&&<p className="text-[10px] font-semibold text-brand-600">Best single store</p>}</div></div>)}</div></div>
      </div>
      <aside className="h-fit overflow-hidden rounded-3xl bg-ink text-white shadow-2xl lg:sticky lg:top-24"><div className="relative p-6"><div className="absolute right-0 top-0 size-40 rounded-full bg-brand-500/20 blur-3xl"/><Pill className="border-brand-400/20 bg-brand-400/10 text-brand-300">{mode === "mixed" ? "Maximum savings" : "Simplest delivery"}</Pill><p className="mt-6 text-sm text-slate-400">Optimized basket total</p><div className="mt-1 flex items-end gap-3"><span className="font-display text-5xl font-extrabold">{money(total)}</span><span className="mb-1.5 text-sm text-slate-500 line-through">₹390</span></div><div className="mt-5 rounded-2xl border border-brand-400/20 bg-brand-400/10 p-4"><p className="text-xs text-brand-300">Your Smart Basket savings</p><p className="mt-1 font-display text-2xl font-bold text-brand-300">{money(390-total)}</p></div>
        <div className="my-6 space-y-3 border-y border-white/10 py-5 text-sm">{mode==="mixed"?<><div className="flex justify-between"><span className="text-slate-400">Fresh Basket · 2 items</span><span>₹190</span></div><div className="flex justify-between"><span className="text-slate-400">Apna Bazaar · 1 item</span><span>₹160</span></div><div className="flex justify-between"><span className="flex items-center gap-1 text-slate-400"><Truck size={14}/> Combined delivery</span><span className="text-brand-300">FREE</span></div></>:<><div className="flex justify-between"><span className="text-slate-400">Apna Bazaar · 3 items</span><span>₹385</span></div><div className="flex justify-between"><span className="text-slate-400">Single delivery</span><span className="text-brand-300">FREE</span></div></>}</div>
        <Button className="h-13 w-full">Choose this plan <ArrowRight size={17}/></Button><p className="mt-3 flex items-center justify-center gap-1 text-[11px] text-slate-500"><Info size={12}/> Prices reserved for the next 10 minutes</p>
      </div></aside>
    </div>
  </div></div>;
}
