"use client";

import Link from "next/link";
import { Check, ChevronRight, Clock3, CreditCard, MapPin, ShieldCheck, WalletCards } from "lucide-react";
import { useState } from "react";
import { createElement } from "react";
import { Button } from "@/components/ui";

export default function CheckoutPage() {
  const [payment, setPayment] = useState("upi");
  return <div className="min-h-screen bg-slate-50 py-10 dark:bg-slate-950"><div className="mx-auto max-w-5xl px-4 sm:px-6"><h1 className="font-display text-4xl font-extrabold">Checkout</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_330px]"><div className="space-y-5">{[[MapPin,"Delivery address","Home · 24, 12th Main, Indiranagar"],[Clock3,"Delivery slot","Today · 6:00 PM – 6:30 PM"]].map(([Icon,title,copy])=><button key={title as string} className="flex w-full items-center gap-4 rounded-2xl border bg-white p-5 text-left dark:border-slate-800 dark:bg-slate-900"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600">{createElement(Icon as typeof MapPin,{size:19})}</span><span className="flex-1"><b className="block">{title as string}</b><span className="mt-1 block text-sm text-slate-500">{copy as string}</span></span><ChevronRight size={18} className="text-slate-400"/></button>)}
        <div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Payment method</h2><div className="mt-4 space-y-3">{[["upi",WalletCards,"UPI","Google Pay, PhonePe, Paytm"],["card",CreditCard,"Credit / debit card","Visa, Mastercard, RuPay"],["cod",ShieldCheck,"Pay on delivery","Cash or UPI at your door"]].map(([id,Icon,title,copy])=><button key={id as string} onClick={()=>setPayment(id as string)} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left ${payment===id?"border-brand-500 bg-brand-50 dark:bg-brand-900/20":"dark:border-slate-700"}`}><span className="grid size-9 place-items-center rounded-lg bg-white shadow-sm dark:bg-slate-800">{createElement(Icon as typeof CreditCard,{size:17})}</span><span className="flex-1"><b className="block text-sm">{title as string}</b><span className="text-xs text-slate-500">{copy as string}</span></span>{payment===id&&<span className="grid size-5 place-items-center rounded-full bg-brand-500 text-white"><Check size={12}/></span>}</button>)}</div></div>
      </div><aside className="h-fit rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Order summary</h2><div className="my-5 space-y-3 text-sm text-slate-500"><div className="flex justify-between"><span>3 items</span><span>₹350</span></div><div className="flex justify-between"><span>Delivery</span><span className="text-brand-600">FREE</span></div><div className="flex justify-between"><span>Platform fee</span><span>₹5</span></div></div><div className="flex justify-between border-t pt-4 text-lg font-bold dark:border-slate-700"><span>Total</span><span>₹355</span></div><Link href="/orders/demo-order"><Button className="mt-6 h-13 w-full">Place order securely</Button></Link><p className="mt-3 text-center text-[11px] text-slate-400">By ordering, you agree to our terms and cancellation policy.</p></aside></div></div></div>;
}
