"use client";

import { Activity, IndianRupee, ShoppingBag, Store, Users } from "lucide-react";
import { StatCard } from "@/components/dashboard-shell";
import { Pill } from "@/components/ui";

export default function AdminDashboard(){
 return <><div><p className="text-xs font-semibold text-brand-600">PLATFORM OVERVIEW</p><h1 className="mt-2 font-display text-3xl font-extrabold">BRIGHTSTORE command centre</h1><p className="mt-1 text-sm text-slate-500">Marketplace health and growth, updated in real time.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="GMV this month" value="₹1.84Cr" change="+24.8%" icon={IndianRupee}/><StatCard label="Orders" value="48,210" change="+19.2%" icon={ShoppingBag} tone="blue"/><StatCard label="Active retailers" value="1,284" change="+84" icon={Store} tone="violet"/><StatCard label="Active users" value="86.4K" change="+12.1%" icon={Users} tone="amber"/><StatCard label="Net revenue" value="₹13.8L" change="+26.7%" icon={Activity}/></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between"><div><h2 className="font-bold">Marketplace GMV</h2><p className="text-xs text-slate-500">Trailing 12 months</p></div><Pill>Live</Pill></div><div className="mt-8 flex h-60 items-end gap-2">{[28,34,31,44,48,53,51,62,67,72,81,92].map((h,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="rounded-t-md bg-gradient-to-t from-brand-600 to-brand-300" style={{height:`${h}%`}}/><span className="text-center text-[9px] text-slate-400">{["J","J","A","S","O","N","D","J","F","M","A","M"][i]}</span></div>)}</div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Platform health</h2><div className="mt-5 space-y-5">{[["API success rate","99.98%","green"],["Order completion","97.4%","green"],["Inventory freshness","94.1%","amber"],["Avg. basket saving","12.8%","green"],["Fraud review queue","14","red"]].map(([label,value,tone])=><div key={label} className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${tone==="green"?"bg-brand-500":tone==="amber"?"bg-amber-500":"bg-rose-500"}`}/><span className="text-sm text-slate-500">{label}</span></div><b className="text-sm">{value}</b></div>)}</div></div></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Retailer approvals</h2><div className="mt-4 space-y-3">{["Sharma Supermart","Green Leaf Organics","Daily Needs Hub"].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl border p-3 dark:border-slate-700"><span className="grid size-9 place-items-center rounded-lg bg-slate-100 text-xs font-bold dark:bg-slate-800">{x[0]}</span><div className="flex-1"><b className="text-xs">{x}</b><p className="text-[10px] text-slate-500">Bengaluru · Submitted {i+1}h ago</p></div><button className="rounded-lg bg-ink px-3 py-2 text-[10px] font-semibold text-white dark:bg-white dark:text-ink">Review</button></div>)}</div></div><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-bold">Top cities by GMV</h2><div className="mt-4 space-y-4">{[["Bengaluru",84],["Delhi NCR",67],["Mumbai",54],["Hyderabad",42]].map(([x,v])=><div key={x as string}><div className="mb-1.5 flex justify-between text-xs"><span>{x as string}</span><b>₹{v as number}L</b></div><div className="h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-slate-900 dark:bg-brand-500" style={{width:`${v}%`}}/></div></div>)}</div></div></div></>;
}
