"use client";

import { ArrowUpRight, Boxes, CircleAlert, IndianRupee, PackageCheck, ShoppingBag, TrendingUp } from "lucide-react";
import { StatCard } from "@/components/dashboard-shell";
import { Button, Pill } from "@/components/ui";

export default function RetailerDashboard() {
  return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold text-brand-600">THURSDAY, 18 JUNE</p><h1 className="mt-2 font-display text-3xl font-extrabold">Good evening, Rajesh.</h1><p className="mt-1 text-sm text-slate-500">Your store is performing 12% better than last week.</p></div><Button><Boxes size={16}/>Add inventory</Button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Revenue today" value="₹24,860" change="+18.4%" icon={IndianRupee}/><StatCard label="Orders today" value="68" change="+12.1%" icon={ShoppingBag} tone="blue"/><StatCard label="Average order" value="₹366" change="+5.2%" icon={TrendingUp} tone="violet"/><StatCard label="Inventory health" value="92%" change="Healthy" icon={Boxes} tone="amber"/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h2 className="font-bold">Revenue</h2><p className="text-xs text-slate-500">Last 7 days</p></div><button className="rounded-lg border px-3 py-2 text-xs dark:border-slate-700">This week</button></div><div className="mt-8 flex h-52 items-end gap-3">{[42,64,51,78,63,88,76].map((h,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="relative rounded-t-lg bg-brand-100 dark:bg-brand-900/30" style={{height:`${h}%`}}><div className="absolute inset-x-0 bottom-0 rounded-t-lg bg-brand-500" style={{height:`${Math.max(28,h-24)}%`}}/></div><span className="text-center text-[10px] text-slate-400">{["F","S","S","M","T","W","T"][i]}</span></div>)}</div></div>
      <div className="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="font-bold">Inventory alerts</h2><Pill>5 need action</Pill></div><div className="mt-5 space-y-3">{[["Amul Taaza Milk","4 left","amber"],["Farm Fresh Bananas","Out of stock","red"],["Tata Salt 1kg","7 left","amber"],["Fortune Oil 1L","9 left","amber"]].map(([name,status,tone])=><div key={name} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><span className={`grid size-8 place-items-center rounded-lg ${tone==="red"?"bg-rose-100 text-rose-600":"bg-amber-100 text-amber-600"}`}><CircleAlert size={15}/></span><div className="flex-1"><p className="text-xs font-semibold">{name}</p><p className="text-[10px] text-slate-500">{status}</p></div><ArrowUpRight size={14} className="text-slate-400"/></div>)}</div></div>
    </div>
    <div className="mt-6 rounded-2xl border bg-white dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b p-5 dark:border-slate-800"><div><h2 className="font-bold">Recent orders</h2><p className="text-xs text-slate-500">Live fulfilment queue</p></div><button className="text-xs font-semibold text-brand-600">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-slate-400"><tr>{["Order","Customer","Items","Amount","Status","Time"].map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{[["#BS-4821","Aarav Sharma","4","₹684","Packing","2m"],["#BS-4820","Meera Iyer","7","₹1,240","Ready","5m"],["#BS-4819","Kabir Singh","2","₹318","Delivered","18m"],["#BS-4818","Sana Khan","5","₹892","Delivered","24m"]].map(row=><tr key={row[0]} className="border-t dark:border-slate-800">{row.map((cell,i)=><td key={i} className="px-5 py-4">{i===4?<span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${cell==="Packing"?"bg-amber-50 text-amber-700":cell==="Ready"?"bg-blue-50 text-blue-700":"bg-brand-50 text-brand-700"}`}>{cell}</span>:cell}</td>)}</tr>)}</tbody></table></div></div>
  </>;
}
