import Link from "next/link";
import { ArrowRight, Minus, Plus, Sparkles, Trash2 } from "lucide-react";
import { products } from "@/lib/data";
import { money } from "@/lib/utils";
import { Button, Pill } from "@/components/ui";

export default function CartPage() {
  const cart = products.slice(0,3);
  return <div className="min-h-screen bg-slate-50 py-10 dark:bg-slate-950"><div className="mx-auto max-w-6xl px-4 sm:px-6"><h1 className="font-display text-4xl font-extrabold">Your basket</h1><p className="mt-2 text-slate-500">3 items from nearby stores</p><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="overflow-hidden rounded-3xl border bg-white dark:border-slate-800 dark:bg-slate-900">{cart.map((p)=><div key={p.id} className="grid grid-cols-[64px_1fr_auto] gap-4 border-b p-5 last:border-0 dark:border-slate-800"><div className="grid size-16 place-items-center rounded-xl bg-slate-100 text-3xl dark:bg-slate-800">{p.emoji}</div><div><h2 className="font-semibold">{p.name}</h2><p className="mt-1 text-xs text-slate-500">{p.unit} · {p.store}</p><p className="mt-2 font-bold">{money(p.price)}</p></div><div className="flex flex-col items-end justify-between"><button className="text-slate-400 hover:text-rose-500"><Trash2 size={16}/></button><div className="flex items-center rounded-lg border dark:border-slate-700"><button className="p-2"><Minus size={12}/></button><span className="px-2 text-xs">1</span><button className="p-2"><Plus size={12}/></button></div></div></div>)}</div>
      <aside className="h-fit rounded-3xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="rounded-2xl bg-ink p-4 text-white"><Pill className="border-brand-400/20 bg-brand-400/10 text-brand-300"><Sparkles size={12}/>Smart Basket ready</Pill><p className="mt-3 text-sm text-slate-300">Save up to <b className="text-brand-300">₹40</b> by splitting across the best stores.</p><Link href="/smart-basket"><Button className="mt-4 w-full">Optimize basket <ArrowRight size={15}/></Button></Link></div><h2 className="mt-6 font-bold">Bill details</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between text-slate-500"><span>Item total</span><span>₹450</span></div><div className="flex justify-between text-slate-500"><span>Delivery</span><span className="text-brand-600">FREE</span></div><div className="flex justify-between border-t pt-4 text-base font-bold dark:border-slate-700"><span>To pay</span><span>₹450</span></div></div><Link href="/checkout"><Button className="mt-6 h-13 w-full">Continue to checkout <ArrowRight size={16}/></Button></Link></aside>
    </div></div></div>;
}
